name: teslo_shop
description: A new Flutter project.
publish_to: "none"
version: 0.2.0

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.3.7
  flutter_riverpod: ^2.4.9
  flutter_staggered_grid_view: ^0.7.0
  formz: ^0.6.1
  go_router: ^6.2.0
  google_fonts: ^4.0.3
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2

dev_dependencies:
  change_app_package_name: ^1.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter_native_splash:
  color: "#e0f2f9"

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/loaders/
    - assets/images/
    - google_fonts/montserrat_alternates/
    - assets/icon/
